### ISSUE TITLE
Существующий конфиг пользователя затирается новым

### ISSUE THREAD

**Issue by sendelufa** [Mark1708/my-vim-setup#1]
хотелось бы возможность именно оценить проект, с возможностью вернуть все как было. Необязательно автоматически.

в sh скрипте безусловно перезаписывается файл конфига, может предварительно заранее сделать копию конфига пользователя, он оценит такую заботу 🫶

**Comment by Mark1708** [comment]
Спасибо, отличная мысль! Обязательно добавлю такую возможность.

**Comment by Mark1708** [comment]
Сделал апдейт)
